### ISSUE TITLE
Installation of ase-espresso

### ISSUE THREAD

**Issue by kuangyia** [vossjo/ase-espresso#29]
Dear developers,

Can we install ase-espresso with "pip" or "conda" ?

Best regards,
Kuangyia

**Comment by vossjo** [comment]
Hello Kuangyia,
The installation of ase-espresso is strongly dependent on the computer cluster setup (scheduler type, local/physical scratch on nodes yes/no etc.) to maximize the performance of the calculations at the prize of a somewhat cumbersome installation.
The [fork](https://github.com/lmmentel/ase-espresso) by Lukasz Mentel is simplified in this context and can be installed via pip.
Best
