### ISSUE TITLE
NotImplementedError: Interactive NEB is not supported

### ISSUE THREAD

**Issue by KS-spec** [vossjo/ase-espresso#34]
Dear all,

I have a question of NEBEspresso.
When I run a example, I have an error : NotImplementedError: Interactive NEB is not supported.
Could you please provide me with a solution or advice?

System information:
Python version:'3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) \n[GCC 9.4.0]'
ase-espresso : '0.3.4'

**input**
-------------------------------------------------------------------
# Optimise molecule.
initial = molecule('C2H6')
initial.calc = EMT()
relax = QuasiNewton(initial,logfile=None)
relax.run(fmax=0.05)
# Create final state.
final = initial.copy()
final.positions[2:5] = initial.positions[[3, 4, 2]]

# Generate blank images.
images = [initial]
for i in range(9):
    images.append(initial.copy())
for image in images:
    image.calc = EMT()
images.append(final)

# Run linear interpolation.
neb = NEBEspresso(images)
neb.interpolate('idpp')

**output**
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[7], line 26
     23 images.append(final)
     25 # Run linear interpolation.
---> 26 neb = NEBEspresso(images)
     27 neb.interpolate('idpp')

File ~/miniforge3/envs/catalyst/lib/python3.8/site-packages/espresso/nebespresso.py:47, in NEBEspresso.__init__(self, images, site, outprefix, **neb_kwargs)
     43 def __init__(self, images, site=None, outprefix="neb", **neb_kwargs):
     45     super().__init__(images, **neb_kwargs)
---> 47     self.site = site
     48     self.outprefix = outprefix
     49     self.jobs = []

File ~/miniforge3/envs/catalyst/lib/python3.8/site-packages/espresso/nebespresso.py:61, in NEBEspresso.site(self, value)
     59     self._site = SiteConfig.check_scheduler()
     60     if self._site.scheduler is None:
---> 61         raise NotImplementedError("Interactive NEB is not supported")
     62 else:
     63     self._site = value

NotImplementedError: Interactive NEB is not supported

**Comment by vossjo** [comment]
The ase-espresso package has not been fully ported to python 3 (I know there are some forks of this repository who have partially ported ase-espresso to python 3). I recommend switching to the official espresso calculator included with ase.
