### ISSUE TITLE
Where is the 3d grid amended?

### ISSUE THREAD

**Issue by mhoffman** [vossjo/ase-espresso#4]
Hi

I am trying to compare electrostatic potentials from different (but commensurate) unit cells. In doing so I noticed that the array describing the potential which read_3d_grid contains one more grid-point in each direction than the corresponding 'tmp.pp'. 

For example my 'tmp.file' contains 64x64x240 grid points as stated in the second line of the file and it correspondingly has 64x64x240=983040 space separated numbers. However the potential returned by this function has one more element along each axis (i.e. 65x65x241) I have  confirmed that the last and first number along each axis is identical, since 

    print(V0[0, :, :] == V0[-1, :, :]).all()                                                                                       
    print(V0[:, 0, :] == V0[:, -1, :]).all()                                                                                       
    print(V0[:, :, 0] == V0[:, :, -1]).all()                   

returns, True in all cases, where V0 is the electrostatic potential. However even after staring at the code defining calc.read_3d_grid() for a pretty long time I cannot tell how I have to clip it to recover the original data.

Any pointers?

Best,
Max.

**Comment by vossjo** [comment]
espresso's pp.x postprocessor adds the periodic image planes to the data for visualization purposes. These periodic image planes should be removed when e.g. integrating over the data.

**Comment by mhoffman** [comment]
Ok, thanks!
