### ISSUE TITLE
[Help] ion_dynamics 'ase3' not allowed

### ISSUE THREAD

**Issue by burning86** [vossjo/ase-espresso#6]
Hi Voss,

I followed your instruction on installation. When I tried to run the example for electrostatic potential. It stopped with the following error message: 
" 
     from  ions_checkin        : error #         1
      ion_dynamics 'ase3' not allowed
"
Could you offer my some suggestion on this error ? Did I miss anything during installation process?
  Thank you very much !

Best

**Comment by vossjo** [comment]
For the 'ase3'-mode to work, you'd need this version of Quantum Espresso:
http://www.qe-forge.org/gf/project/q-e/scmsvn/?action=browse&path=%2Fbranches%2Fespresso-dynpy-beef%2F
( svn co --username anonymous http://qeforge.qe-forge.org/svn/q-e/branches/espresso-dynpy-beef )
Or you can use
calc=espresso(......, mode='scf', .......)
which will work with all (sufficiently recent) versions of espresso.

**Comment by burning86** [comment]
Ah, Got it. It works now. Thank you so much !

PS, I have met another problem during compilation of espresso-dynpy-beef. The error came around compiling "tddfpt" (I don't need this function so far, thus I comment it off afterwards). The error message was below

make[3]: *** No rule to make target `../../Modules/environ_input.o', needed by `bcast_lr_input.o'.  Stop.
make[3]: Leaving directory `/home/brightzhang/code/espresso-dynpy-beef/TDDFPT/src'
make[2]: *** [tddfpt] Error 1
make[2]: Leaving directory `/home/brightzhang/code/espresso-dynpy-beef/TDDFPT'
make[1]: *** [tddfpt] Error 1
make[1]: Leaving directory `/home/brightzhang/code/espresso-dynpy-beef/install'
make: *** [tddfpt] Error 1

Sincerely appreciated for your help !
